function err = F(x, inputArgs, benchmarks)


[data.y, data.Gender, data.DeathCause, data.Last, data.DeathYear, data.NaturalDeathYear,...
    data.DirectCancer, data.DirectCancerR, data.DirectCancer2, data.DirectCancer2R,...
    data.ProgressedCancer, data.ProgressedCancerR, data.TumorRecord,...
    data.DwellTimeProgression, data.DwellTimeFastCancer,...
    data.HasCancer, data.NumPolyps, data.MaxPolyps, data.AllPolyps, data.NumCancer, data.MaxCancer,...
    data.PaymentType, data.Money, data.Number, data.EarlyPolypsRemoved,...
    data.DiagnosedCancer, data.AdvancedPolypsRemoved, data.YearIncluded, data.YearAlive, data.PBP_Doc]...
    = NumberCrunching(inputArgs);

data.InputCost = inputArgs.Cost;
data.InputCostStage = inputArgs.CostStage;

[data,BM] = Evaluation_for_Jan_Sept_2019_lean(data, initialCalibration); % ,Step,Iter); BM



end